- 👋 Hi, I’m @hammsandwitch
- 👀 I’m interested in becoming a better programmer.
- 🌱 I’m currently learning how to work with django to create a minimum viable product.
- 📫 You can reach me at theandrewmccleary@gmail.com
